# -*- coding: utf-8 -*-
"""Loan-RFC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZL1WYzQ5KnI08tTX3ZXns7t0G3bU52u

**Loan Approval Model - Random Forest Classifier**

Internal Working - Trains multiple decision trees with random subsets of training data

Classification - It predicts the final class by taking the majority of the predictions from all the decision trees

Let's import the necessary packages

Pandas - load , store, clean and manipulate the dataset required
"""

import pandas as pd

"""Train test split from model selection - to split our dataset into training and testing dataset to evaluate the model's accuracy finally"""

from sklearn.model_selection import train_test_split

"""Importing random forest algorithm"""

from sklearn.ensemble import RandomForestClassifier

"""Accuracy score from metrics to find how many predictions comes right"""

from sklearn.metrics import accuracy_score

"""Confusion matrix and classification report to analyse the model's prediction"""

from sklearn.metrics import classification_report,confusion_matrix

"""GridSearchCV for finding the best parameters for the random forest classifier model"""

from sklearn.model_selection import GridSearchCV

"""Numpy for numerical computations and array operations"""

import numpy as np

df=pd.read_csv("data.csv")
df.head()

"""X - input features for the models which will consist everything except Loan Status"""

X=df.drop("Loan_Status",axis=1)

"""y - Final Prediction - > Loan Status"""

y=df["Loan_Status"]

"""Let's pre process our x data using one hot encoding"""

X=pd.get_dummies(X,drop_first=True)
X.head()

"""Let's pre process the y dataset using label Encoding"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

"""Splitting the dataset into training and testing"""

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

"""Let's train the model"""

rf=RandomForestClassifier(
    n_estimators=100,
    criterion="gini",
    random_state=42
)
rf.fit(X_train,y_train)

y_pred=rf.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
print()
print(confusion_matrix(y_test,y_pred))
print()
print(classification_report(y_test,y_pred))

